### ISSUE TITLE
Default values can lead to invalid builds

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-grpc-quickstart-java.g8#28]
In https://github.com/akka/akka-grpc-quickstart-java.g8/blob/master/src/main/g8/default.properties#L3-L8 user may opt into `2.13` but dependencies will be set to `akka-grpc-runtime_2.12` and `akka-actor_2.12`.

**Comment by ennru** [comment]
Would it be better to hard-code Scala 2.13 versions in the Java template?

**Comment by ignasi35** [comment]
> Would it be better to hard-code Scala 2.13 versions in the Java template?

SGTM.

**Comment by ennru** [comment]
Part of #38

**Comment by ignasi35** [comment]
Yep, part of #38
