### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by shankarshastri** [akka/akka-grpc-quickstart-java.g8#3]
I know that repo just started today 😄. And I know that still WIP.
1. Repo Name? akka-grpc-quickstart-java.g8?
2. Adding this in quickstart in https://grpc.io/

**Comment by raboof** [comment]
Thanks for your feedback!  Does the repo name still need a change? It seems OK to me now?

Adding Akka gRPC to grpc.io is a great idea, added an issue for it at https://github.com/akka/akka-grpc/issues/409

**Comment by shankarshastri** [comment]
@raboof, Repo name looks ok now 😄.

**Comment by shankarshastri** [comment]
Closing this issue, as another issue is already taking care of it.
